### PR TITLE
Run based on whether we've seen every day in the month.

### PR DESCRIPTION
**Pull request by abayer**
Currently we're stuck waiting 'til the logs for the first day of the
next month are available before we start processing, since that's the
easiest way to tell that we've actually got every day for the
month. That annoys me, so here's a tweak that instead makes sure we've
got at least one logfile for every day of a given month and proceeds
if that's the case.

cc @rtyler @batmat

### CODE REVIEW

**Comment by rtyler** [comment]
@batmat this looks fine to me, but you've touched this code more recently than I have so I will wait for your :+1: to merge

**Comment by batmat** [comment]
I fear this is going to screw many stats, many not but... I remember having checked explicitly that recently in the code. 

Oh now I remember, for example, in my case (and probably/maybe?) others, I `select .... where month = select max(month) from plugins` or so. If the `max(month)` now becomes the current one, then stats are never going to be good, or say only the last day of the month...

I guess we'd need to check, but I fear this is a risky one for the current stats "health".

Alternatively, maybe we just want to leave the code as-is and push it when it's currently. And add a switch to push ongoing stats somewhere else/in another subdirectory?

**Comment by abayer** [comment]
So any stats analysis will be unchanged by this - all it does is do the import on the first day of the month rather than the second. We don't process the raw logs for a given month until we see at least one raw log file for the *next* month currently. This just changes to process the raw logs when we've seen raw log files for every day of a month.

**Comment by batmat** [comment]
Yeah, and also, now that I had a more precise look at the code, it's actually the code processing raw logs to `json.gz`, so in any case that shouldn't impact "downstream" stats calculations. So :+1:

**Comment by abayer** [comment]
Other PRs made this pointless.

**Pull request closed without merging**
