### PR TITLE
Add jvms.json to the list

### PR DESCRIPTION
**Pull request by batmat**
As rightly requested by @daniel-beck in https://github.com/jenkins-infra/infra-statistics/pull/21#issuecomment-256900365

### CODE REVIEW

**Comment by batmat** [comment]
Note: @daniel-beck: your comment "why in plugins-installation-trend" is right. It's not logical, though installations or capabilities are also already not in their right place. 

Should we just rename that whole dir to `installation-trends` to be consistent and put a rewrite rule in place? cc @rtyler

**Comment by batmat** [comment]
BTW, note to self, I should really also generate a .csv file. Easier to graph with std tools...

**Comment by rtyler** [comment]
@batmat this is deployed via GitHub Pages so there are HTML redirects but no re-write rules.

I'm going to start smacking people with :fish: who keep suggesting adding mod_rewrite rules to our infrastructure is a good idea :smiling_imp:

**Comment by batmat** [comment]
Ping @rtyler @daniel-beck is zis mergeable? Thanks

**Comment by rtyler** [comment]
(shrug)

**Pull request merged**
